02-12-2023 09:06:52 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    303
----------------------------------------
02-12-2023 09:06:52 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    303
----------------------------------------
02-12-2023 09:06:52 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:06:52 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:07:30 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    303
----------------------------------------
02-12-2023 09:07:30 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    303
----------------------------------------
02-12-2023 09:07:30 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:07:30 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:08:07 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    303
----------------------------------------
02-12-2023 09:08:07 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    303
----------------------------------------
02-12-2023 09:08:07 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:08:07 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:09:01 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    304
----------------------------------------
02-12-2023 09:09:01 AM | ERROR | Exception occurred while trying to speak.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  os.remove(audio_file)
Message: cannot access local variable 'audio_file' where it is not associated with a value
Line:    304
----------------------------------------
02-12-2023 09:09:01 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:09:01 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: Exception occurred while trying to speak.
Line:    1151
----------------------------------------
02-12-2023 09:09:09 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1095ba110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:09:12 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1095ba290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:09:15 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:09:15 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:05 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10803fc50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:08 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108237c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:11 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:11 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:14 AM | ERROR | "Jarvis" Not Available.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  voice_text = self.recognizer.recognize_google(audio)
Message: recognition connection failed: [Errno 8] nodename nor servname provided, or not known
Line:    128
----------------------------------------
02-12-2023 09:47:14 AM | ERROR | "Jarvis" Not Available.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  voice_text = self.recognizer.recognize_google(audio)
Message: recognition connection failed: [Errno 8] nodename nor servname provided, or not known
Line:    128
----------------------------------------
02-12-2023 09:47:14 AM | ERROR | General Error while running virtual assistant. 
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  elif sleep_counter > 0 and _wake_assistant(listen_time):
Message: "Jarvis" Not Available.
Line:    1064
----------------------------------------
02-12-2023 09:47:14 AM | ERROR | General Error while running virtual assistant. 
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  elif sleep_counter > 0 and _wake_assistant(listen_time):
Message: "Jarvis" Not Available.
Line:    1064
----------------------------------------
02-12-2023 09:47:14 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: General Error while running virtual assistant. 
Line:    1151
----------------------------------------
02-12-2023 09:47:14 AM | ERROR | Error while starting virtual assistant.
File:    /Users/jairo/DEV/Python/VirtualAssistant/assitant.py
Target:  _start_virtual_assistant()
Message: General Error while running virtual assistant. 
Line:    1151
----------------------------------------
02-12-2023 09:47:27 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10753b3d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:30 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10753bcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:33 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:33 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:35 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107546c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:38 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107547290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:41 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:41 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:43 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10755d690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:46 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10755dc90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:49 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:49 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:51 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10755ffd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:53 AM | INFO | Error occurred while parsing html. HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: /latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1082364d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
02-12-2023 09:47:54 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10755f490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:47:57 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:57 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:47:59 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10756aa50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:02 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10756b0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:05 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:05 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:07 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107579450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:10 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1075798d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:13 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:13 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:15 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10757bbd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:18 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10757b2d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:21 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:21 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:23 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1075825d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:26 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107582c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:29 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:29 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:31 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107588fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:34 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107589490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:37 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:37 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:39 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10758b990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:42 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10758ba10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:45 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:45 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:47 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1075a2390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:50 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1075a2a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 09:48:53 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:53 AM | ERROR | Error while initiating telegram bot.
File:    /Users/jairo/DEV/Python/VirtualAssistant/tts.py
Target:  if check_connection("Telegram bot"):
Message: Connection error, maximum retries already exhausted...
Line:    193
----------------------------------------
02-12-2023 09:48:55 AM | ERROR | Internet Connection Error. You are not connected to the Internet.
File:    /Users/jairo/DEV/Python/VirtualAssistant/helper.py
Target:  response = requests.get("http://google.com", timeout=300)
Message: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1075acdd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
Line:    167
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
02-12-2023 04:29:48 PM | INFO | Error occurred while parsing rss feed. Remote end closed connection without response
02-13-2023 11:28:28 AM | INFO | Dave: give me tips on how to  effectively refresh my memory and prepare for an interview for reactjs developer role
02-13-2023 11:28:42 AM | INFO | Jarvis: 

1. Refresh your knowledge of the React library and its features, such as components, state, props, and hooks.

2. Review and practice coding challenges related to React, such as solving coding problems or writing simple programs.

3. Read through React-related blog posts or articles to stay up to date with the latest trends and best practices.

4. Research the company, and familiarize yourself with their product and technologies they use.

5. Practice explaining your React projects and how you used React to solve the problem.

6. Practice talking through your development process and how you debugged React problems.

7. Prepare questions to ask your interviewer to demonstrate your interest in the role and the company. 

8. Make sure you are comfortable using React tools such as React Developer Tools and create-react-app.

9. Refresh your knowledge of HTML, CSS, and JavaScript since React relies heavily on these languages.

10. Practice coding on a whiteboard to simulate an actual coding interview.
02-13-2023 11:32:30 AM | INFO | Dave: what's the meaning of life in why is it answered 42
02-13-2023 11:32:35 AM | INFO | Jarvis: 

The meaning of life is a philosophical question that has been debated for centuries. The number 42 is a reference to the book The Hitchhiker's Guide to the Galaxy by Douglas Adams, in which a supercomputer is asked to calculate the meaning of life and responds with the answer 42.
