08-01-2020 05:47:26 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:48:16 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:48:47 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:48:56 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 05:54:33 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:54:34 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:54:37 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023964F71CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:54:37 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023964F71850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:54:40 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:57:04 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:57:46 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5DC07AE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:57:46 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5DC07AD00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:57:46 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: /latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5DC07AAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:57:46 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5DC0D0460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:57:46 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F5DC0D0340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 05:57:46 PM | ERROR | ------------------------------------------------------------
08-01-2020 05:58:02 PM | ERROR | ------------------------------------------------------------
08-01-2020 06:07:35 PM | ERROR | ------------------------------------------------------------
08-01-2020 06:40:35 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: ('Connection aborted.', OSError("(10053, 'WSAECONNABORTED')"))
Line:    245
08-01-2020 06:40:37 PM | ERROR | ------------------------------------------------------------
08-01-2020 07:36:26 PM | ERROR | ------------------------------------------------------------
08-01-2020 07:43:48 PM | ERROR | ------------------------------------------------------------
08-01-2020 07:53:18 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 07:53:18 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 07:53:18 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 07:53:18 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 07:53:18 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:53:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 08:57:03 PM | ERROR | ------------------------------------------------------------
08-01-2020 08:59:01 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 10:04:29 PM | ERROR | ------------------------------------------------------------
08-01-2020 10:06:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 10:06:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 10:06:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 10:06:23 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Time stamp to date/time conversion error.
Target:  return dt(year, month, (day - value), hour, minute).strftime("%A, %d %b %Y %I:%M %p")
Message: day is out of range for month
Line:    93
08-01-2020 10:28:50 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
Line:    245
08-01-2020 11:00:29 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:01:36 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:02:00 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:15:54 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:17:59 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:18:24 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:34:00 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000261021731F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 11:34:00 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026102173610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 11:34:04 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:34:39 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:34:42 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:34:42 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:34:47 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:34:53 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026101EEED60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 11:34:53 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026101EEE8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 11:35:50 PM | ERROR | ------------------------------------------------------------
08-01-2020 11:35:53 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026102F7F400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-01-2020 11:35:53 PM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026102F7F760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Line:    245
08-02-2020 04:45:22 AM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
Line:    245
08-02-2020 04:45:22 AM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
Line:    245
08-02-2020 04:45:22 AM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
Line:    245
08-02-2020 04:45:22 AM | ERROR | ------------------------------------------------------------
08-02-2020 04:45:28 AM | CRITICAL | C:\Users\Dave\DEVENV\Python\NewsScraper\NewsScraper.py
File:  Error occurred while parsing html.
Target:  response = requests.get(self.url)
Message: HTTPSConnectionPool(host='cnnphilippines.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
Line:    245
08-02-2020 10:20:12 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:20:45 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:21:49 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:27:17 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:27:31 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:30:31 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:34:51 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:36:01 AM | ERROR | ------------------------------------------------------------
08-02-2020 10:44:52 AM | ERROR | ------------------------------------------------------------
08-02-2020 11:31:51 AM | ERROR | ------------------------------------------------------------
08-02-2020 11:48:05 AM | ERROR | ------------------------------------------------------------
08-02-2020 11:51:15 AM | ERROR | ------------------------------------------------------------
08-02-2020 11:55:54 AM | ERROR | ------------------------------------------------------------
08-02-2020 11:57:39 AM | ERROR | ------------------------------------------------------------
08-02-2020 11:59:15 AM | ERROR | ------------------------------------------------------------
08-02-2020 12:08:36 PM | ERROR | ------------------------------------------------------------
08-02-2020 01:23:02 PM | ERROR | ------------------------------------------------------------
08-02-2020 01:24:38 PM | ERROR | ------------------------------------------------------------
08-02-2020 03:23:21 PM | ERROR | ------------------------------------------------------------
